//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TSchool.h
//  @ Date : 22.03.2023
//  @ Author : 
//
//


#if !defined(_TSCHOOL_H)
#define _TSCHOOL_H

#include "TPupil.h"

class TSchool {
public:
	TSchool(string name);
	void printData();
	void setData(string name, int age);
	string getName();
	void setName(string name);
private:
	TPupil m_pupil;
	string m_name;
};

#endif  //_TSCHOOL_H
