//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TSchool.cpp
//  @ Date : 22.03.2023
//  @ Author : 
//
//

#include "TSchool.h"

TSchool::TSchool(string name) {
    m_name = name;
    std::cout << name << "\n";
}

void TSchool::printData() {
    std::cout << m_pupil.getName() << "\n";
    std::cout << m_pupil.getAge() << "\n";
}

void TSchool::setData(string name, int age) {
    m_pupil.setName(name);
    m_pupil.setAge(age);
}

string TSchool::getName() {
    return m_name;
}

void TSchool::setName(string name) {
    m_name = name;
}

