//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TPupil.h
//  @ Date : 29.03.2023
//  @ Author : 
//
//

#include <iostream>
#include <string>
#include <vector>

using namespace std;

#if !defined(_TPUPIL_H)
#define _TPUPIL_H


class TPupil {
public:
	TPupil();
	~TPupil();
	string getName();
	int getAge();
	void setName(string name);
	void setAge(int age);
private:
	string m_pupillName;
	int m_pupilAge;
};

#endif  //_TPUPIL_H
