//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TSchool.cpp
//  @ Date : 29.03.2023
//  @ Author :
//
//

#include "TSchool.h"

TSchool::TSchool(string name)
{
    m_name = name;
}

void TSchool::printData()
{
    std::cout << "Nazwa szkoly to: " << m_name << "\n";
}

void TSchool::attach(TPupil *pupil)
{
    m_pupils.push_back(pupil);
    std::cout << "Dolaczono ucznia\n";
}

void TSchool::detach()
{
    if (!m_pupils.empty())
    {
        std::cout << "Odlaczono ostatniego ucznia\n";
        m_pupils.pop_back();
    }
    else
    {
        std::cout << "Nie zostal zaden uczen do odlaczenia\n";
    }
}

void TSchool::detachAll(){
    while (!m_pupils.empty())
    {
        std::cout << "Odlaczono ucznia\n";
        m_pupils.pop_back();
    }

    std::cout << "Wszyscy uczniowie zostali odlaczeni\n"; 
}

void TSchool::printData(int i)
{
    std::cout << "Uczen o indeksie " << i << " nazywa sie: "
              << m_pupils[i]->getName() << " i ma " << m_pupils[i]->getAge() << " lat \n";
}

void TSchool::setData(int i, string name, int age)
{
    m_pupils[i]->setName(name);
    m_pupils[i]->setAge(age);
}
