//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TSchool.h
//  @ Date : 29.03.2023
//  @ Author : 
//
//


#if !defined(_TSCHOOL_H)
#define _TSCHOOL_H

#include "TPupil.h"

class TSchool {
public:
	TSchool(string name);
	void printData();
	void attach(TPupil* pupil);
	void detach();
	void detachAll();
	void printData(int i);
	void setData(int i, string name, int age);
private:
	string m_name;
	vector<TPupil*> m_pupils;
};

#endif  //_TSCHOOL_H
