//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Konto.h
//  @ Date : 31.05.2023
//  @ Author : 
//
//


#if !defined(_KONTO_H)
#define _KONTO_H

#include "Uczelnia.h"

class Konto {
public:
	void zalogujSie(int id, string haslo);
	int getId();
	void setId(int id);
	string getHaslo();
	void setHaslo(string haslo);
	bool getStatusZalogowania();
	void setStatusZalogowania(bool status);
	string getNazwisko();
	void setNazwisko(string nazwisko);
	string getImie();
	void setImie(string imie);
	string testNazwiskoImie();
private:
	int id;
	string haslo;
	bool statusZalogowania;
	string nazwisko;
	string imie;
	Uczelnia* uczelnia;
};

#endif  //_KONTO_H
