//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Konto.cpp
//  @ Date : 31.05.2023
//  @ Author : 
//
//

#include "Konto.h"

void Konto::zalogujSie(int id, string haslo) {
    setStatusZalogowania(true);
    cout << "Zalogowano " << id << "\n";
}

int Konto::getId() {
    return id;
}

void Konto::setId(int id) {
    this->id = id;
}

string Konto::getHaslo() {
    return haslo;
}

void Konto::setHaslo(string haslo) {
    this->haslo = haslo;
}

bool Konto::getStatusZalogowania() {
    return statusZalogowania;
}

void Konto::setStatusZalogowania(bool status) {
    this->statusZalogowania = status;
}

string Konto::getNazwisko() {
    return nazwisko;
}

void Konto::setNazwisko(string nazwisko) {
    this->nazwisko = nazwisko;
}

string Konto::getImie() {
    return imie;
}

void Konto::setImie(string imie) {
    this->imie = imie;
}

string Konto::testNazwiskoImie() {
    return (getNazwisko() + " " + getImie());
}

