//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Kurs.cpp
//  @ Date : 31.05.2023
//  @ Author : 
//
//


#include "Kurs.h"

Kurs::Kurs() {

}

Kurs::~Kurs() {

}

void Kurs::wyswietlInformacje() {

}

int Kurs::getId() {

}

string Kurs::getTytul() {

}

Prowadzacy* Kurs::getProwadzacy() {

}

int Kurs::getLimitStudentow() {

}

void Kurs::setLimitStudentow(int limitStudentow) {

}

string Kurs::getSylabus() {

}

void Kurs::setNewKursData(string tytul, int limitStudentow, string sylabus, Prowadzacy* idProwadzacego) {

}

void Kurs::dodajOcene(Student* student, double ocena) {

}

void Kurs::edytujOcene(Student* student, double ocena) {

}

vector<double>* Kurs::testOceny(vector<double>* ocenyKontener) {

}

string Kurs::testKursData() {

}

bool Kurs::zapiszStudenta(Student* student) {

}

