//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Kurs.h
//  @ Date : 31.05.2023
//  @ Author : 
//
//


#if !defined(_KURS_H)
#define _KURS_H

#include "Uczelnia.h"

class Kurs {
public:
	Kurs();
	~Kurs();
	void wyswietlInformacje();
	int getId();
	string getTytul();
	Prowadzacy* getProwadzacy();
	int getLimitStudentow();
	void setLimitStudentow(int limitStudentow);
	string getSylabus();
	void setNewKursData(string tytul, int limitStudentow, string sylabus, Prowadzacy* idProwadzacego);
	void dodajOcene(Student* student, double ocena);
	void edytujOcene(Student* student, double ocena);
	vector<double>* testOceny(vector<double>* ocenyKontener);
	string testKursData();
private:
	int id;
	string tytul;
	Prowadzacy* prowadzacy;
	int limitStudentow;
	string sylabus;
	vector<Student*> studenciUczeszczajacy;
	map<Student*, double> oceny;
	Uczelnia* uczelnia;
	bool zapiszStudenta(Student* student);
};

#endif  //_KURS_H
