//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Prowadzacy.h
//  @ Date : 31.05.2023
//  @ Author : 
//
//


#if !defined(_PROWADZACY_H)
#define _PROWADZACY_H

#include "Uczelnia.h"
#include "Kurs.h"
#include "Konto.h"

class Prowadzacy : public Konto {
public:
	Prowadzacy(int id, string nazwisko, string imie);
	~Prowadzacy();
	void dodajKurs();
	void edytujKurs();
	void dodajOcene();
	void edytujOcene();
private:
	vector<Kurs*> prowadziKursy;
	void dodajKursPoprawny(string tytul, int limitStudentow, string sylabus, Prowadzacy* idProwadzacego);
	void edytujKursPoprawny(string tytul, int limitStudentow, string sylabus, int idProwadzacego);
	void dodajOcenePoprawnie(Kurs* kurs, Student* student, double ocena);
	void edytujOcenePoprawnie(Kurs* kurs, Student* student, double ocena);
};

#endif  //_PROWADZACY_H
