//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Student.cpp
//  @ Date : 31.05.2023
//  @ Author : 
//
//


#include "Student.h"

Student::Student(int indeks, string nazwisko, string imie) {

}

Student::~Student() {

}

void Student::dodajDoKursu(Kurs* kurs) {

}

void Student::przegladajKursy() {

}

void Student::wyslijWniosek() {

}

void Student::zapiszSieNaKurs(Kurs* kurs, Student* indeks) {

}

void Student::wyslijWniosekPoprawnie(Wniosek* wniosek, string tytul, string tresc) {

}

