//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Uczelnia.h
//  @ Date : 31.05.2023
//  @ Author : 
//
//


#include <iostream>
#include <vector>
#include <string>
#include <utility>
#include <map>

using namespace std;

#if !defined(_UCZELNIA_H)
#define _UCZELNIA_H

class Student;
class Wniosek;
class Prowadzacy;
class Kurs;

class Uczelnia {
public:
	Uczelnia();
	~Uczelnia();
	void addStudent(Student* student);
	void addProwadzacy(Prowadzacy* prowadzacy);
private:
	vector<Student*> studenci;
	vector<Prowadzacy*> prowadzacy;
};

#endif  //_UCZELNIA_H
