//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Uczelnia.cpp
//  @ Date : 31.05.2023
//  @ Author : 
//
//


#include "Uczelnia.h"

Uczelnia::Uczelnia() {
	vector<Student*> studenci;
	vector<Prowadzacy*> prowadzacy;
    cout << "Uczelnia stworzona\n";
}

Uczelnia::~Uczelnia() {
    cout << "Uczelnia zniszczona\n";
}

void Uczelnia::addStudent(Student* student) {
    this->studenci.push_back(student);
    cout << "Dodano studenta do uczelni\n";
}

void Uczelnia::addProwadzacy(Prowadzacy* prowadzacy) {
    this->prowadzacy.push_back(prowadzacy);
    cout << "Dodano prowadzacego do uczelni\n";
}

