//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Wniosek.cpp
//  @ Date : 31.05.2023
//  @ Author : 
//
//

#include "Wniosek.h"

Wniosek::Wniosek() {
    cout << "Wniosek zostal utworzony\n";
}

Wniosek::~Wniosek() {
    cout << "Wniosek zostal zniszczony\n";
}

string Wniosek::getTytul() {
    return tytul;
}

string Wniosek::getTresc() {
    return tresc;
}

void Wniosek::setData(string tytul, string tresc) {
    this->tytul = tytul;
    this->tresc = tresc;
}

void Wniosek::wyslijWniosek(string tytul, string tresc) {
    cout << "Wniosek o tytule " << tytul << " zostal wyslany\n";
}

string Wniosek::testData() {
    return (getTytul() + " " + getTresc());
}

