//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : THeart.cpp
//  @ Date : 23.03.2023
//  @ Author : 
//
//


#include <iostream>
#include "THeart.h"

THeart::THeart(int heartRate, float size) {
    std::cout << "Konstruktor klasy THeart\n";
    m_heartRate = heartRate;
    m_size = size;
}

THeart::~THeart() {
    std::cout << "Destruktor klasy THeart\n";

}

int THeart::getHeartRate() {
    return m_heartRate;
}

float THeart::getSize() {
    return m_size;
}

void THeart::setHeartRate(int heartRate) {
    m_heartRate = heartRate;
}

void THeart::setSize(float size) {
    m_size = size;
}

