//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TBook.cpp
//  @ Date : 22.03.2023
//  @ Author : 
//
//

#include "TBook.h"
#include "TReader.h"

string TBook::getTitle() {
    return m_title;
}

string TBook::getAuthor() {
    return m_author;
}

TReader* TBook::getReader() {
    return m_reader;
}

void TBook::setTitle(string title) {
    m_title = title;
}

void TBook::setAuthor(string author) {
    m_author = author;
}

void TBook::setReader(TReader* reader) {
    m_reader = reader;
}

