//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TBook.h
//  @ Date : 22.03.2023
//  @ Author : 
//
//
#include <string>



using namespace std;
#if !defined(_TBOOK_H)
#define _TBOOK_H

class TReader;

class TBook {
public:
	string getTitle();
	string getAuthor();
	TReader* getReader();
	void setTitle(string title);
	void setAuthor(string author);
	void setReader(TReader* reader);
private:
	string m_title;
	string m_author;
	TReader* m_reader;
};

#endif  //_TBOOK_H
