//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TReader.cpp
//  @ Date : 22.03.2023
//  @ Author : 
//
//


#include "TReader.h"
#include "TBook.h"

TBook* TReader::getBook() {
    return m_book;
}

string TReader::getName() {
    return m_name;
}

string TReader::getSurname() {
    return m_surname;
}

void TReader::setBook(TBook* book) {
    m_book = book;
}

void TReader::setName(string name) {
    m_name = name;
}

void TReader::setSurname(string surname) {
    m_surname = surname;
}

