//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TReader.h
//  @ Date : 22.03.2023
//  @ Author : 
//
//

#if !defined(_TREADER_H)
#define _TREADER_H
#include "TBook.h"

class TReader {
public:
	TBook* getBook();
	string getName();
	string getSurname();
	void setBook(TBook* book);
	void setName(string name);
	void setSurname(string surname);
private:
	string m_name;
	string m_surname;
	TBook* m_book;
};

#endif  //_TREADER_H
