//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ClassB.cpp
//  @ Date : 23.03.2023
//  @ Author : 
//
//


#include "ClassB.h"

void ClassB::funB(ClassA* classA) {
    classA->funA();
}

