//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ClassB.h
//  @ Date : 23.03.2023
//  @ Author : 
//
//


#if !defined(_CLASSB_H)
#define _CLASSB_H

#include "ClassA.h"

class ClassB {
public:
	void funB(ClassA* classA);
private:
	ClassA* m_classA;
};

#endif  //_CLASSB_H
