//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ClassA.h
//  @ Date : 23.03.2023
//  @ Author : 
//
//
#include <iostream>
using namespace std;

#if !defined(_CLASSA_H)
#define _CLASSA_H


class ClassA {
public:
	ClassA();
	void funA();
private:
	int i;
};

#endif  //_CLASSA_H
