//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ClassA.cpp
//  @ Date : 23.03.2023
//  @ Author : 
//
//


#include "ClassA.h"

ClassA::ClassA() {
    i = 10;
}

void ClassA::funA() {
    std::cout << "Operacja klasy\n";
    i *= 10;
    std::cout << i << "\n";
}

