//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Database.cpp
//  @ Date : 25.05.2023
//  @ Author :
//
//

#include "Database.h"

Database *Database::m_database = nullptr;

Database *Database::getInstance()
{
    if (!Database::m_database)
    {
        m_database = new Database;
    }
    return m_database;
}

Database::Database()
{
}

vector<Table *> Database::getTables()
{
    return m_tables;
}

void Database::addTable(Table *table)
{
    m_tables.push_back(table);
}

void Database::deleteTable(Table *table)
{
    for (auto it = m_tables.begin(); it != m_tables.end(); it++)
    {
        if (*it == table)
        {
            delete *it;         
            m_tables.erase(it); 
            break;              
        }
    }
}
