//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Table.h
//  @ Date : 25.05.2023
//  @ Author : 
//
//

#include <string>
#include <iostream>

using namespace std;

#if !defined(_TABLE_H)
#define _TABLE_H


class Table {
public:
	Table(string columnName, string dataType, string size, string constrains);
	void printTable();
private:
	string m_columnName;
	string m_dataType;
	string m_size;
	string m_constrains;
};

#endif  //_TABLE_H
