//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Table.cpp
//  @ Date : 25.05.2023
//  @ Author : 
//
//


#include "Table.h"

Table::Table(string columnName, string dataType, string size, string constrains) {
    m_columnName = columnName;
    m_dataType = dataType;
    m_size = size;
    m_constrains = constrains;
}

void Table::printTable(){
    std::cout << m_columnName << "\n";
    std::cout << m_dataType << "\n";
    std::cout << m_size << "\n";
    std::cout << m_constrains << "\n";
}

