//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : THuman.cpp
//  @ Date : 23.03.2023
//  @ Author : 
//
//


#include "THuman.h"

THuman::THuman() {
    m_heart = new THeart(99, 30);
}

THuman::~THuman() {
    delete m_heart;
}

void THuman::printData() {
    std::cout << m_heart->getHeartRate() << "\n";
    std::cout << m_heart->getSize() << "\n";
}

void THuman::setData(int heartRate, float size) {
    m_heart->setHeartRate(heartRate);
    m_heart->setSize(size);
}

