//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : THuman.h
//  @ Date : 23.03.2023
//  @ Author : 
//
//
#include <string>
#include <iostream>

using namespace std;
#if !defined(_THUMAN_H)
#define _THUMAN_H

#include "THeart.h"

class THuman {
public:
	THuman();
	~THuman();
	void printData();
	void setData(int heartRate, float size);
private:
	THeart* m_heart;
	string m_sex;
};

#endif  //_THUMAN_H
