//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : BezdomneZwierzeSchronisko.cpp
//  @ Date : 27.05.2023
//  @ Author : 
//
//


#include "BezdomneZwierzeSchronisko.h"

Bezdomne* BezdomneZwierzeSchronisko::stworz() {
    return new BezdomneZwierzeSchronisko;
}





