//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Bezdomne.h
//  @ Date : 27.05.2023
//  @ Author : 
//
//


#if !defined(_BEZDOMNE_H)
#define _BEZDOMNE_H


class Bezdomne {
public:
	virtual ~Bezdomne() = default;
	virtual void adoptuj() = 0;
	virtual void poglaskaj() = 0;
};

#endif  //_BEZDOMNE_H
