//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : HDDDrive.cpp
//  @ Date : 21.06.2023
//  @ Author : 
//
//


#include "HDDDrive.h"

void HDDDrive::displayDevice() {
    std::cout << "HDD Drive\n";
}

