//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : HDDDrive.h
//  @ Date : 21.06.2023
//  @ Author : 
//
//


#if !defined(_HDDDRIVE_H)
#define _HDDDRIVE_H

#include "IDrive.h"
#include <iostream>

class HDDDrive : public IDrive {
public:
	void displayDevice();
};

#endif  //_HDDDRIVE_H
