//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : HDDDeviceFactory.cpp
//  @ Date : 21.06.2023
//  @ Author : 
//
//


#include "HDDDeviceFactory.h"


IDrive* HDDDeviceFactory::drive() {
    return new HDDDrive;

}

IDevice* HDDDeviceFactory::device() {

    return new HDDDevice;
}

