//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : HDDDevice.h
//  @ Date : 21.06.2023
//  @ Author : 
//
//


#if !defined(_HDDDEVICE_H)
#define _HDDDEVICE_H

#include <iostream>	
#include "IDevice.h"

class HDDDevice : public IDevice {
public:
	void displayDevice();
};

#endif  //_HDDDEVICE_H
