//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : HDDDevice.cpp
//  @ Date : 21.06.2023
//  @ Author : 
//
//


#include "HDDDevice.h"

void HDDDevice::displayDevice() {
    std::cout << "HDD Device\n";
}

