//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : IDeviceFactory.h
//  @ Date : 21.06.2023
//  @ Author : 
//
//


#if !defined(_IDEVICEFACTORY_H)
#define _IDEVICEFACTORY_H

#include "IDevice.h"
#include "IDrive.h"

class IDeviceFactory {
public:
	virtual IDevice* device() = 0;
	virtual IDrive* drive() = 0;
};

#endif  //_IDEVICEFACTORY_H
