//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : IDevice.h
//  @ Date : 21.06.2023
//  @ Author : 
//
//


#if !defined(_IDEVICE_H)
#define _IDEVICE_H
#include <iostream>

class IDevice {
public:
	virtual void displayDevice() = 0;
};

#endif  //_IDEVICE_H
