//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : IDrive.h
//  @ Date : 21.06.2023
//  @ Author : 
//
//


#if !defined(_IDRIVE_H)
#define _IDRIVE_H


class IDrive {
public:
	virtual void displayDevice() = 0;
};

#endif  //_IDRIVE_H
