//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SSDDrive.h
//  @ Date : 21.06.2023
//  @ Author : 
//
//


#if !defined(_SSDDRIVE_H)
#define _SSDDRIVE_H

#include "IDrive.h"
#include <iostream>

class SSDDrive : public IDrive {
public:
	void displayDevice();
};

#endif  //_SSDDRIVE_H
