//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SSDDrive.cpp
//  @ Date : 21.06.2023
//  @ Author : 
//
//


#include "SSDDrive.h"

void SSDDrive::displayDevice() {
    std::cout << "SSD Drive\n";

}

