//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SSDDevice.cpp
//  @ Date : 21.06.2023
//  @ Author : 
//
//


#include "SSDDevice.h"

void SSDDevice::displayDevice() {
    std::cout << "SSD Device\n";

}

