//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SSDDevice.h
//  @ Date : 21.06.2023
//  @ Author : 
//
//


#if !defined(_SSDDEVICE_H)
#define _SSDDEVICE_H

#include "IDevice.h"

class SSDDevice : public IDevice {
public:
	void displayDevice();
};

#endif  //_SSDDEVICE_H
