//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SSDDeviceFactory.cpp
//  @ Date : 21.06.2023
//  @ Author : 
//
//


#include "SSDDeviceFactory.h"



IDrive* SSDDeviceFactory::drive() {
    return new SSDDrive;
}

IDevice* SSDDeviceFactory::device() {
    return new SSDDevice;
}

