//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TBuilding.h
//  @ Date : 28.03.2023
//  @ Author : 
//
//

#if !defined(_TBUILDING_H)
#define _TBUILDING_H

#include "TRoom.h"


class TBuilding {
public:
	TBuilding();
	~TBuilding();
	void printData();
	void setData(string rType, float rSquareMeters);
private:
	TRoom* m_room;
	string m_type;
	float m_squareMeters;
};

#endif  //_TBUILDING_H
