//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TRoom.h
//  @ Date : 28.03.2023
//  @ Author : 
//
//

#include <iostream>
#include <string>

using namespace std;

#if !defined(_TROOM_H)
#define _TROOM_H


class TRoom {
public:
	TRoom();
	~TRoom();
	string getType();
	float getSquareMeters();
	void setType(string type);
	void setSquareMeters(float squareMeters);
private:
	string m_type;
	float m_squareMeters;
};

#endif  //_TROOM_H
