//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ISubscriber.h
//  @ Date : 24.05.2023
//  @ Author : 
//
//

#include <string>
#include <iostream>
using namespace std;

#if !defined(_ISUBSCRIBER_H)
#define _ISUBSCRIBER_H


class ISubscriber {
public:
	virtual ~ISubscriber() = default;
	virtual void Update(string message) = 0;
};

#endif  //_ISUBSCRIBER_H
