//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Publisher.cpp
//  @ Date : 24.05.2023
//  @ Author : 
//
//


#include "Publisher.h"

Publisher::~Publisher() {
    std::cout << "Publisher has been deleted\n";
}

void Publisher::Attach(ISubscriber* subscriber) {
    m_subscribers.insert(subscriber);
}

void Publisher::Detach(ISubscriber* subscriber) {
    m_subscribers.erase(subscriber);
}

void Publisher::Notify() {

    for(auto subscriber : m_subscribers){
        subscriber->Update(m_message);
    }
}

void Publisher::CreateMessage(string message) {
    m_message = message;
    Notify();
}

void Publisher::HowManyObservers() {
    std::cout << "There are " << m_subscribers.size() << "subscribers to this thread\n";
}