//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Subscriber.h
//  @ Date : 24.05.2023
//  @ Author : 
//
//


#if !defined(_SUBSCRIBER_H)
#define _SUBSCRIBER_H

#include "ISubscriber.h"
#include "Publisher.h"

class Subscriber : public ISubscriber {
public:
	Subscriber(Publisher* publisher, string name);
	virtual ~Subscriber();
	void Update(string message) override;
	void Unsubscribe();
	void PrintInfo();
private:
	string m_name;
	string m_message;
	Publisher* m_publisher;
};

#endif  //_SUBSCRIBER_H
