//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Subscriber.cpp
//  @ Date : 24.05.2023
//  @ Author : 
//
//


#include "Subscriber.h"

Subscriber::Subscriber(Publisher* publisher, string name) {
    m_publisher = publisher;
    m_name = name;
    m_publisher->Attach(this);
    std::cout << "Hi, I am a subscriber " << m_name << "\n";
}

Subscriber::~Subscriber() {
    std::cout << "Goodby, I was " << m_name << "\n";
}

void Subscriber::Update(string message) {
    m_message = message;
    PrintInfo();
}

void Subscriber::Unsubscribe() {
    m_publisher->Detach(this);
    std::cout << "Subscriber " << m_name << " has left the thread\n";
}

void Subscriber::PrintInfo() {
    std::cout << "Subscriber: " << m_name << " new message about the thread has arrived\n";
}

