//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Bank.h
//  @ Date : 23.05.2023
//  @ Author : 
//
//

#include <iostream>

#if !defined(_BANK_H)
#define _BANK_H

class Bank {
public:
	void doSomething();
};

#endif  //_BANK_H
