//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Bank.cpp
//  @ Date : 23.05.2023
//  @ Author : 
//
//

#include "Bank.h"

void Bank::doSomething() {
    std::cout << "Operacja banku\n";
}

