//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Klient.h
//  @ Date : 23.05.2023
//  @ Author : 
//
//

#include <string>
#include <iostream>


using namespace std;

#if !defined(_KLIENT_H)
#define _KLIENT_H
#include "Ksiegowy.h"


class Klient {
public:
	void makeOperation(Ksiegowy* ksiegowy);
private:
	string name;
	string surname;
	int accountBalance;
};

#endif  //_KLIENT_H
