//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Klient.cpp
//  @ Date : 23.05.2023
//  @ Author : 
//
//


#include "Klient.h"

void Klient::makeOperation(Ksiegowy* ksiegowy) {
    ksiegowy->mainOperation();
}

