//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ksiegowy.cpp
//  @ Date : 23.05.2023
//  @ Author : Ezdies
//
//


#include "Ksiegowy.h"

Ksiegowy::Ksiegowy(Bank* bank = nullptr, 
Skarbowka* skarbowka = nullptr) {
    m_bank = bank ? bank : new Bank;
    m_skarbowka = skarbowka ? skarbowka : new Skarbowka;
}

Ksiegowy::~Ksiegowy(){
    delete m_bank;
    delete m_skarbowka;
}

void Ksiegowy::mainOperation(){
    std::cout << "Operacje sa wywolywane przez fasade\n";
    m_bank->doSomething();
    m_skarbowka->doSomething();
}

