//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ksiegowy.h
//  @ Date : 23.05.2023
//  @ Author : 
//
//

#include "Bank.h"
#include "Skarbowka.h"

#if !defined(_KSIEGOWY_H)
#define _KSIEGOWY_H


class Ksiegowy {
public:
	Ksiegowy(Bank* bank, Skarbowka* skarbowka);
	~Ksiegowy();
	void mainOperation();
private:
	Bank* m_bank;
	Skarbowka* m_skarbowka;
};

#endif  //_KSIEGOWY_H
