//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Skarbowka.cpp
//  @ Date : 23.05.2023
//  @ Author : 
//
//


#include "Skarbowka.h"

void Skarbowka::doSomething() {
    std::cout << "Operacja skarbowki\n";
}

