//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Skarbowka.h
//  @ Date : 23.05.2023
//  @ Author : 
//
//

#include <iostream>

#if !defined(_SKARBOWKA_H)
#define _SKARBOWKA_H

class Skarbowka {
public:
	void doSomething();
};

#endif  //_SKARBOWKA_H
