//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TApartment.h
//  @ Date : 30.03.2023
//  @ Author : 
//
//


#if !defined(_TAPARTMENT_H)
#define _TAPARTMENT_H

#include "TOccupant.h"

class TApartment {
public:
	TApartment();
	TApartment(string standard, float squareMeters, int roomCount, float rentCost, int numberOfRenovations, int value);
	~TApartment();
	string getStandard();
	void setStandard(string standard);
	float getSquareMeters();
	void setSquareMeters(float squareMeters);
	float getRentCost();
	void setRentCost(float rentCost);
	int getNumberOfRenovations();
	void setNumberOfRenovations(int numberOfRenovations);
	int getRoomCount();
	void setRoomCount(int roomCount);
	int getValue();
	void setValue(int value);
	void renovateApartment(TOccupant* occupant);
private:
	string m_standard;
	float m_squareMeters;
	int m_roomCount;
	float m_rentCost;
	int m_numberOfRenovations;
	int m_value;
};

#endif  //_TAPARTMENT_H
