//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TBlock.cpp
//  @ Date : 30.03.2023
//  @ Author : 
//
//


#include "TBlock.h"

TBlock::TBlock(int value, int addressNumber, float totalSquareMeters, int numberOfApartments, int happyTenants) {
    m_totalValue = value;
    m_addressNumber = addressNumber;
    m_totalSquareMeters = totalSquareMeters;
    m_numberOfApartments = numberOfApartments;
    m_happyTenants = happyTenants;
    
    m_apartments.resize(m_numberOfApartments);

    for (int i = 0; i < m_numberOfApartments; i++){
        std::cout << "Tworze mieszkanie " << i + 1 << '\n';
        m_apartments[i] = new TApartment;
    }
}

TBlock::~TBlock() {

    for (int i = 0; i < m_numberOfApartments; i++){
        std::cout << "Usuwam mieszkanie " << i + 1 << '\n';
        delete m_apartments[i];
    }
    std::cout << "Usunieto blok \n";
}

void TBlock::printData() {
    for (int i = 0; i < m_numberOfApartments; i++){
        std::cout << "Mieszkanie " << i + 1 << '\n';
        std::cout << m_apartments[i]->getStandard() << "\n";
        std::cout << m_apartments[i]->getSquareMeters() << "\n";
        std::cout << m_apartments[i]->getRoomCount() << "\n";
        std::cout << m_apartments[i]->getRentCost() << "\n";
        std::cout << m_apartments[i]->getNumberOfRenovations() << "\n";
        std::cout << m_apartments[i]->getValue() << "\n";
    }
}

void TBlock::appraise() {
    std::cout << "Wycena budynku: " << m_totalValue << "\n"; 
}

