//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TOccupant.h
//  @ Date : 30.03.2023
//  @ Author : 
//
//

#include <string>
#include <iostream>
#include <vector>

using namespace std;

#if !defined(_TOCCUPANT_H)
#define _TOCCUPANT_H


class TOccupant {
public:
	int getHappinessLevel();
	void setHappinessLevel(int happinessLevel);
	void doRenovation();
private:
	int m_happinessLevel = 0;
};

#endif  //_TOCCUPANT_H
