//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : THouse.cpp
//  @ Date : 23.03.2023
//  @ Author : 
//
//


#include "THouse.h"

string THouse::getAddress() {

}

void THouse::setAddress(string address) {

}

int THouse::getValue() {

}

void THouse::setValue(int value) {

}

