//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : THouse.h
//  @ Date : 23.03.2023
//  @ Author : 
//
//


#if !defined(_THOUSE_H)
#define _THOUSE_H


class THouse {
public:
	string getAddress();
	void setAddress(string address);
	int getValue();
	void setValue(int value);
private:
	string m_address;
	int m_value;
};

#endif  //_THOUSE_H
