//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TOwner.cpp
//  @ Date : 23.03.2023
//  @ Author : 
//
//


#include "TOwner.h"

THouse* TOwner::getHouse() {
    return m_house;
}

void TOwner::setHouse(THouse* house) {
    m_house = house;
}

string TOwner::getName() {
    return m_name;
}

void TOwner::setName(string name) {
    m_name = name;
}

string TOwner::getSurname() {
    return m_surname;
}

void TOwner::setSurname(string surname) {
    m_surname = surname;
}

void TOwner::attach() {
    //tworzymy dom

    m_houses.push_back(m_house);

}

void TOwner::detach() {

}

