//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TOwner.h
//  @ Date : 23.03.2023
//  @ Author : 
//
//

#include <iostream>
#include <string>
#include <vector>

using namespace std;

#include "THouse.h";

#if !defined(_TOWNER_H)
#define _TOWNER_H


class TOwner {
public:
	THouse* getHouse();
	void setHouse(THouse* house);
	string getName();
	void setName(string name);
	string getSurname();
	void setSurname(string surname);
	void attach();
	void detach();
private:
	string m_name;
	string m_surname;
	THouse* m_house;
	vector<THouse*> m_houses;
};

#endif  //_TOWNER_H
