//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Jamnik.h
//  @ Date : 09.03.2023
//  @ Author : 
//
//


#if !defined(_JAMNIK_H)
#define _JAMNIK_H

#include "Pies.h"
#include <string>
#include <iostream>

using namespace std;

class Jamnik : public Pies {
public:
	float podajWage();
	string podajImie();
	void ustawWage(float waga);
	void ustawImie(string imie);
	void zaszczekaj();
	void aportuj();
private:
	float m_waga;
	string m_imie;
};

#endif  //_JAMNIK_H
