//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Jamnik.cpp
//  @ Date : 09.03.2023
//  @ Author : 
//
//


#include "Jamnik.h"


using namespace std;

float Jamnik::podajWage() {
    return m_waga;

}

string Jamnik::podajImie() {
    return m_imie;
}

void Jamnik::ustawWage(float waga) {
    m_waga = waga;
}

void Jamnik::ustawImie(string imie) {
    m_imie = imie;
}

void Jamnik::zaszczekaj() {
    std::cout << "Hau hau\n";
}

void Jamnik::aportuj() {
    std::cout << "Przyniosl kosc\n";

}

