//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pies.h
//  @ Date : 09.03.2023
//  @ Author : 
//
//


#if !defined(_PIES_H)
#define _PIES_H

#include "Ssak.h"
#include <string>
using namespace std;

class Pies : public Ssak {
public:
	string podajRase();
	string podajSiersc();
	void ustawRase(string rasa);
	void ustawSiersc(string siersc);
private:
	string m_rasa;
	string m_siersc;
};

#endif  //_PIES_H
