//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pies.cpp
//  @ Date : 09.03.2023
//  @ Author : 
//
//


#include "Pies.h"


string Pies::podajRase() {
    return m_rasa;
}

string Pies::podajSiersc() {
    return m_siersc;
}

void Pies::ustawRase(string rasa) {
    m_rasa = rasa;

}

void Pies::ustawSiersc(string siersc) {
    m_siersc = siersc;
}

