//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.cpp
//  @ Date : 09.03.2023
//  @ Author : 
//
//


#include "Ssak.h"

int Ssak::podajWiek() {
    return m_wiek;
}

string Ssak::podajUmaszczenie() {
    return m_umaszczenie;
}

void Ssak::ustawWiek(int wiek) {
    m_wiek = wiek;
}

void Ssak::ustawUmaszczenie(string umaszczenie) {
    m_umaszczenie = umaszczenie;
}

