//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.h
//  @ Date : 09.03.2023
//  @ Author : 
//
//


#if !defined(_SSAK_H)
#define _SSAK_H

#include <string>
using namespace std;


class Ssak {
public:
	int podajWiek();
	string podajUmaszczenie();
	void ustawWiek(int wiek);
	void ustawUmaszczenie(string umaszczenie);
private:
	int m_wiek;
	string m_umaszczenie;
};

#endif  //_SSAK_H
