//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : System.h
//  @ Date : 19.04.2023
//  @ Author : 
//
//

#include <iostream>
#include <vector>

using namespace std;

class User;

#if !defined(_SYSTEM_H)
#define _SYSTEM_H

#include "User.h"

class System {
public:
	void addNewUser(User* user);
	void verifyUser(User* user);
	bool isRegistered(User* user);
	bool isLoggedIn(User* user);
private:
	vector<User*> m_users;
};

#endif  //_SYSTEM_H
