//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : User.cpp
//  @ Date : 19.04.2023
//  @ Author :
//
//

#include "User.h"

void User::login(System *system)
{
    std::cout << "\nLogowanie:\n";
    std::cout << "Podaj nazwe\n";
    std::cin >> m_username;
    std::cout << "Podaj haslo\n";
    std::cin >> m_password;
    setUsername(m_username);
    setPassword(m_password);
    system->verifyUser(this);
    this->m_isLoggedIn = true;
}

void User::logout(System* system) {
    std::string decision;
    std::cout << "Czy chcesz sie wylogowac (tak|nie)\n";
    std::cin >> decision;
    if (decision == "tak") {
        this->m_isLoggedIn = false;
        std::cout << "You have been logged out.\n";
    } else {
        this->m_isLoggedIn = true;
        std::cout << "Okay, you are still logged in.\n";
    }
}


void User::registerMe(System *system)
{
    std::cout << "\nRejestracja:\n";
    std::cout << "Podaj nazwe\n";
    std::cin >> m_username;
    std::cout << "Podaj haslo\n";
    std::cin >> m_password;
    this->m_isRegistered = true;
}

string User::getUsername()
{
    return m_username;
}

void User::setUsername(string username)
{
    m_username = username;
}

string User::getPassword()
{
    return m_password;
}

void User::setPassword(string password)
{
    m_password = password;
}

bool User::getIsRegistered()
{
    return m_isRegistered;
}

bool User::getIsLoggedIn()
{
    return m_isLoggedIn;
}
