//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : User.h
//  @ Date : 19.04.2023
//  @ Author : 
//
//

#include "System.h"

#if !defined(_USER_H)
#define _USER_H

class System;

class User {
public:
	void login(System* system);
	void logout(System* system);
	void registerMe(System* system);
	string getUsername();
	void setUsername(string username);
	string getPassword();
	void setPassword(string password);
	bool getIsRegistered();
	bool getIsLoggedIn();
private:
	string m_username;
	string m_password;
	bool m_isLoggedIn;
	bool m_isRegistered;
};

#endif  //_USER_H
